_target_: lasaft.data.audioset_dataprovider.DataProvider
audioset_root: ${audioset_dir}
batch_size: 8
num_workers: 0
pin_memory: True
num_frame: 128
hop_length: 1024
n_fft: 2048
multi_source_training: False