defaults:
  - trainer: default
  - dataset: audioset
  - callbacks: default
  - model: audioset_v1
  - logger: wandb
  - exp: null


debug: False
seed: null

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# personal settings
audioset_dir: ${oc.env:audioset_dir}
dev_data_dir: ${oc.env:dev_data_dir}
wandb_api_key: ${oc.env:wandb_api_key}

dataset:
  batch_size: 1
hydra:
  run:
    dir: logs/runs/${model.name}/${now:%Y%m%d-%H%M%S}
