evaluate.results_folder: 'results/'
log_file.path: './logs/log.txt'

autoclip.percentile: 10

signal.hop_length: 128
signal.sample_rate: $sample_rate
signal.window_length: 512
signal.window_type: sqrt_hann

evaluate.folder: $test_folder
evaluate.num_workers: 1

logger.level: info

mixer.coherent_prob: 0.25
mixer.augment_prob: 0.5
mixer.quick_pitch_time_prob: 1.0

mixer.master_label: vocals
mixer.duration: 5.0
mixer.sample_rate: $sample_rate
mixer.n_channels: 1
mixer.num_mixtures: 10
mixer.ref_db: [-30, -10]
mixer.snr: [uniform, -5.0, 0]
mixer.target_snr_boost: 2.5
mixer.source_file: [choose, []]
mixer.time_stretch: [uniform, .9, 1.1]
mixer.pitch_shift: [uniform, -2, 2]


mixer.overfit_seed: 0

train/mixer.fg_path: $train_folder
train/mixer.duration: 5.0
train/mixer.num_mixtures: 10000000

val/mixer.fg_path: $val_folder
val/mixer.duration: 30.0
val/mixer.coherent_prob: 1.0
val/mixer.augment_prob: 0.0
val/mixer.num_mixtures: 1000

test/mixer.fg_path: $test_folder
test/mixer.duration: 30.0
test/mixer.coherent_prob: 1.0
test/mixer.augment_prob: 0.0
test/mixer.num_mixtures: 1000

device.use: cuda

early_stopping.cumulative_delta: 0
early_stopping.epochs: 30
early_stopping.min_delta: 0.0

patience.epochs: 5
patience.factor: 0.5
patience.mode: min
patience.verbose: false

transform.audio_only: false
transform.mask_type: msa
